"use client";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.css";
import { Inter } from "next/font/google";
import Navbar from "./component/Navbar";
import Footer from "./component/footer";
import { Provider } from "react-redux";
import store from "./store";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  console.log({ children }, "children");
  return (
    // <section>
    //   <Navbar />
    //   {children}
    //   <Footer />
    // </section>
    <html lang="en">
      <body className={inter.className}>
        <Provider store={store}>
          <section>
            <Navbar />
            {children}
            <Footer />
          </section>
        </Provider>
      </body>
    </html>
  );
}
