import "./../globals.css";
import "bootstrap/dist/css/bootstrap.css";
import { Inter } from "next/font/google";
import Navbar from "./component/Navbar";
import Footer from "./component/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  console.log({ children }, "children");
  return (
    <section>
      <Navbar />
      {children}
      <Footer />
    </section>
  );
}
